=== AdamWill/os-autoinst-distri-fedora-ai-test/schemas/fif-predefault.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "fif-incomplete.json",
  "type": "object",
  "title": "Schema for Fedora Intermediate Format (FIF) openQA job template data before products defaults merge",
  "anyOf": [
    { "required": [ "Machines" ]},
    { "required": [ "Products" ]},
    { "required": [ "Profiles" ]},
    { "required": [ "TestSuites" ]}
  ],
  "properties": {
    "Machines": { "$ref": "fif-machines.json" },
    "Flavors": { "$ref": "fif-flavors.json" },
    "ProductDefaults": { "$ref": "fif-productdefaults.json" },
    "Products": { "$ref": "fif-products-predefault.json" },
    "ProfileGroups": { "$ref": "fif-profilegroups.json" },
    "Profiles": { "$ref": "fif-profiles.json" },
    "TestSuites": { "$ref": "fif-testsuites.json" },
    "JobTemplates": { "$ref": "openqa-jobtemplates.json" }
  },
  "additionalProperties": false
}

=== AdamWill/os-autoinst-distri-fedora-ai-test/templates-updates.fif.json
{
    "Flavors": {
        "updates-cloud": {
            "settings": {
                "HDD_1": "Fedora.%ARCH%-%VERSION%.qcow2",
                "ISO": "cloudinit.iso",
                "KIWI_PROFILE": "Cloud-Base-Generic",
                "NUMDISKS": "2",
                "RETRY": "1",
                "+START_AFTER_TEST": "kiwi_build@%ARCH_BASE_MACHINE%",
                "SUBVARIANT": "Cloud"
            }
        },
        "updates-container": {
            "settings": {
                "+HDD_1": "disk_f%VERSION%_server_5_%ARCH%.qcow2",
                "KIWI_PROFILE": "Container-Base-Generic",
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-everything-boot-iso": {
            "settings": {
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-kde": {
            "settings": {
                "+HDD_1": "disk_f%VERSION%_kde_5_%ARCH%.qcow2",
                "DESKTOP": "kde",
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-server": {
            "settings": {
                "+HDD_1": "disk_f%VERSION%_server_5_%ARCH%.qcow2",
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-server-upgrade": {
            "settings": {
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-silverblue-dvd_ostree-iso": {
            "settings": {
                "CANNED": "1",
                "DESKTOP": "gnome",
                "DEPLOY_UPLOAD_TEST": "install_default_update_ostree",
                "HDDSIZEGB": "15",
                "NUMDISKS": "2",
                "PACKAGE_SET": "default",
                "RETRY": "2",
                "SUBVARIANT": "Silverblue"
            }
        },
        "updates-workstation-live-iso": {
            "settings": {
                "DESKTOP": "gnome",
                "HDDSIZEGB": "15",
                "KIWI_PROFILE": "Workstation-Live",
                "LIVE": "1",
                "NUMDISKS": "2",
                "PACKAGE_SET": "default",
                "RETRY": "1",
                "SUBVARIANT": "Workstation"
            }
        },
        "updates-kde-live-iso": {
            "settings": {
                "DESKTOP": "kde",
                "HDDSIZEGB": "15",
                "KIWI_PROFILE": "KDE-Desktop-Live",
                "LIVE": "1",
                "NUMDISKS": "2",
                "PACKAGE_SET": "default",
                "RETRY": "1",
                "SUBVARIANT": "KDE"
            }
        },
        "updates-workstation-upgrade": {
            "settings": {
                "DESKTOP": "gnome",
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        },
        "updates-workstation": {
            "settings": {
                "DESKTOP": "gnome",
                "+HDD_1": "disk_f%VERSION%_desktop_5_%ARCH%.qcow2",
                "NUMDISKS": "2",
                "RETRY": "1"
            }
        }
    },
    "ProductDefaults": {
        "distri": "fedora",
        "group_name": "Fedora Updates",
        "version": "*"
    },
    "Products": {
        "fedora-updates-cloud-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-cloud"
        },
        "fedora-updates-container-aarch64-*": {
            "arch": "aarch64",
            "flavor": "updates-container",
            "group_name": "Fedora AArch64 Updates"
        },
        "fedora-updates-container-ppc64le-*": {
            "arch": "ppc64le",
            "flavor": "updates-container",
            "group_name": "Fedora PowerPC Updates"
        },
        "fedora-updates-container-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-container"
        },
        "fedora-updates-everything-boot-iso-aarch64-*": {
            "arch": "aarch64",
            "flavor": "updates-everything-boot-iso",
            "group_name": "Fedora AArch64 Updates"
        },
        "fedora-updates-everything-boot-iso-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-everything-boot-iso"
        },
        "fedora-updates-kde-aarch64-*": {
            "arch": "aarch64",
            "flavor": "updates-kde",
            "group_name": "Fedora AArch64 Updates"
        },
        "fedora-updates-kde-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-kde"
        },
        "fedora-updates-server-aarch64-*": {
            "arch": "aarch64",
            "flavor": "updates-server",
            "group_name": "Fedora AArch64 Updates"
        },
        "fedora-updates-server-ppc64le-*": {
            "arch": "ppc64le",
            "flavor": "updates-server",
            "group_name": "Fedora PowerPC Updates"
        },
        "fedora-updates-server-upgrade-ppc64le-*": {
            "arch": "ppc64le",
            "flavor": "updates-server-upgrade",
            "group_name": "Fedora PowerPC Updates"
        },
        "fedora-updates-server-upgrade-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-server-upgrade"
        },
        "fedora-updates-server-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-server"
        },
        "fedora-updates-silverblue-dvd_ostree-iso-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-silverblue-dvd_ostree-iso"
        },
        "fedora-updates-workstation-live-iso-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-workstation-live-iso"
        },
        "fedora-updates-kde-live-iso-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-kde-live-iso"
        },
        "fedora-updates-workstation-upgrade-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-workstation-upgrade"
        },
        "fedora-updates-workstation-aarch64-*": {
            "arch": "aarch64",
            "flavor": "updates-workstation",
            "group_name": "Fedora AArch64 Updates"
        },
        "fedora-updates-workstation-x86_64-*": {
            "arch": "x86_64",
            "flavor": "updates-workstation"
        }
    },
    "Profiles": {
        "fedora-updates-cloud-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-cloud-x86_64-*"
        },
        "fedora-updates-container-aarch64-*-aarch64": {
            "machine": "aarch64",
            "product": "fedora-updates-container-aarch64-*"
        },
        "fedora-updates-container-ppc64le-*-ppc64le": {
            "machine": "ppc64le",
            "product": "fedora-updates-container-ppc64le-*"
        },
        "fedora-updates-container-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-container-x86_64-*"
        },
        "fedora-updates-everything-boot-iso-aarch64-*-aarch64": {
            "machine": "aarch64",
            "product": "fedora-updates-everything-boot-iso-aarch64-*"
        },
        "fedora-updates-everything-boot-iso-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-everything-boot-iso-x86_64-*"
        },
        "fedora-updates-everything-boot-iso-x86_64-*-bios": {
            "machine": "bios",
            "product": "fedora-updates-everything-boot-iso-x86_64-*"
        },
        "fedora-updates-kde-aarch64-*-aarch64": {
            "machine": "aarch64",
            "product": "fedora-updates-kde-aarch64-*"
        },
        "fedora-updates-kde-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-kde-x86_64-*"
        },
        "fedora-updates-server-aarch64-*-aarch64": {
            "machine": "aarch64",
            "product": "fedora-updates-server-aarch64-*"
        },
        "fedora-updates-server-ppc64le-*-ppc64le": {
            "machine": "ppc64le",
            "product": "fedora-updates-server-ppc64le-*"
        },
        "fedora-updates-server-upgrade-ppc64le-*-ppc64le": {
            "machine": "ppc64le",
            "product": "fedora-updates-server-upgrade-ppc64le-*"
        },
        "fedora-updates-server-upgrade-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-server-upgrade-x86_64-*"
        },
        "fedora-updates-server-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-server-x86_64-*"
        },
        "fedora-updates-kde-live-iso-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-kde-live-iso-x86_64-*"
        },
        "fedora-updates-kde-live-iso-x86_64-*-bios": {
            "machine": "bios",
            "product": "fedora-updates-kde-live-iso-x86_64-*"
        },
        "fedora-updates-silverblue-dvd_ostree-iso-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-silverblue-dvd_ostree-iso-x86_64-*"
        },
        "fedora-updates-silverblue-dvd_ostree-iso-x86_64-*-bios": {
            "machine": "bios",
            "product": "fedora-updates-silverblue-dvd_ostree-iso-x86_64-*"
        },
        "fedora-updates-workstation-live-iso-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-workstation-live-iso-x86_64-*"
        },
        "fedora-updates-workstation-live-iso-x86_64-*-bios": {
            "machine": "bios",
            "product": "fedora-updates-workstation-live-iso-x86_64-*"
        },
        "fedora-updates-workstation-upgrade-x86_64-*-64bit": {
            "machine": "64bit",
            "product": "fedora-updates-workstation-upgrade-x86_64-*"
        },
        "fedora-updates-workstation-aarch64-*-aarch64": {
            "machine": "aarch64",
            "product": "fedora-updates-workstation-aarch64-*"
        },
        "fedora-updates-workstation-x86_64-*-64bit": {
            "machine": "64bit",
